version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

parameters:
  project:
    type: enum
    enum: ["dss", "dsm","api-docs", "nothing"]
    default: "dss"

workflows:
  filter-based-on-changes-workflow:
    jobs:
      - path-filtering/filter:
          name: check-files
          base-revision: TryToGetCircleCiMonoRepoToWork
          config-path: .circleci/main-config.yml
          mapping: |
            pepper-apis/docs/.* project api-docs
